### ISSUE TITLE
Data collection process

### ISSUE THREAD

**Issue by mfala097** [albud187/ELG5163_project#9]
- [x] 1 - burgerbot driver - to drive burgerbot in test paths
- [x] 2 - data collector - collect and save data (distance) from trial runs: graph chart, 
   x = time;
   y= distance;
   line 1: Desired distance (const);
   line 2: Lidar distance;
   line 3: Distance_calculator distance;;

**Comment by albud187** [comment]
needs 2 nodes:
1 - burgerbot driver - to drive burgerbot in test paths
2 - data collector - collect and save data from trial runs
